apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: voting
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-deployer
  namespace: voting
rules:
# Core (namespaced) resources
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - services
    - endpoints
    - configmaps
    - secrets
    - persistentvolumeclaims
  verbs: ["get","list","watch","create","update","patch","delete"]

# Workloads
- apiGroups: ["apps"]
  resources: ["deployments","replicasets","daemonsets","statefulsets"]
  verbs: ["get","list","watch","create","update","patch","delete"]

# HPA
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get","list","watch","create","update","patch","delete"]

# Ingress
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","list","watch","create","update","patch","delete"]

# (optional) batch jobs if you add them later
- apiGroups: ["batch"]
  resources: ["jobs","cronjobs"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-deployer
  namespace: voting
subjects:
- kind: ServiceAccount
  name: ci-deployer
  namespace: voting
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-deployer
