apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: voting
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-deployer
  namespace: voting
rules:
  - apiGroups: ["", "apps", "extensions", "networking.k8s.io"]
    resources:
      - deployments
      - services
      - ingresses
      - configmaps
      - pods
      - pods/log
      - replicasets
      - endpoints
      - events
      - persistentvolumeclaims
    verbs: ["get","list","watch","create","update","patch","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-deployer
  namespace: voting
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: voting
roleRef:
  kind: Role
  name: ci-deployer
  apiGroup: rbac.authorization.k8s.io
