apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: voting
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
