apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: voting
  labels:
    app: vote
spec:
  type: ClusterIP
  selector:
    app: vote
  ports:
    - name: http
      port: 80
      targetPort: 80
